name: Simple workflow

on: [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a string
              run: eccho "Hello string"
            - name: multiline script
              run: |
                  node -v
                  npm -v

    run-python-commands:
        needs: ["run-shell-command"]
        runs-on: ubuntu-latest
        steps:
            - name: Python command
              run: |
                  import platform
                  print(platform.processor())
              shell: python
